name: invite-a-gent
services:
  dynamodb:
    image: amazon/dynamodb-local:2.6.1
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    ports:
      - "${DYNAMODB_PORT:-18000}:8000"
    volumes:
      - ./.dynamodb:/data
